### ISSUE TITLE
key generation help

### ISSUE THREAD

**Issue by zosorock** [AleoHQ/aleo-setup#292]
I feel that when you run 
`aleo-setup-contributor generate -h` 
the binary should print information like the parameters
`--keys-path aleo-contrib-key.json`
at the very least, and perhaps mention the passphrase requirement (i.e. cannot be left blank).

**Comment by ibaryshnikov** [comment]
Thanks for your feedback! Can you provide a bit more information on what could be changed? For example, by editing existing help message in a way you'd like to see it. At the moment it prints:
```
$ aleo-setup-contributor generate --help
aleo-setup-contributor-generate 0.4.0
Generate a seed and an Aleo private key for contribution

USAGE:
    aleo-setup-contributor generate [OPTIONS] --keys-path <keys-path>

FLAGS:
    -h, --help    Prints help information

OPTIONS:
        --keys-path <keys-path>      Store the seed and private key at the given path
        --passphrase <passphrase>    The passphrase to use for encrypting the private key. If unspecified, the
                                     passphrase will be requested via tty or pinentry dialog
```

As far as I know, `--passphrase` is intended for tests only, because we use `pinentry` for this purpose in real environment
